apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tr3o3kfng-python
  janus-idp.io/tekton: tr3o3kfng-python
  backstage.io/kubernetes-id: tr3o3kfng-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tr3o3kfng-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
