apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tr3o3kfng-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tr3o3kfng-python 
  name: tr3o3kfng-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tr3o3kfng-python 
